server:
  workers: auto
  trustProxy: true
mysql:
  url: mysql://root:MySQLRootPassword@mariadb:3306/sync_in
auth:
  token:
    access:
      secret: changeAccessWithStrongSecret
    refresh:
      secret: changeRefreshWithStrongSecret
applications:
  files:
    dataPath: /app/data
    maxUploadSize: 5368709120 # 5 GB
    onlyoffice:
      enabled: false
      secret: onlyOfficeSecret